[package]
name = "brevy_os"
version = "0.1.0"
edition = "2024"

[workspace]
members = ["kernel"]
# default-members = ["kernel"]

[dependencies]
ovmf-prebuilt = "0.2.4"

[build-dependencies]
brevyos = { path = "kernel", artifact = "bin", target = "x86_64-unknown-none" }
bootloader = "0.11"

[profile.dev]
panic = "abort"

[profile.release]
panic = "abort"
